name: CD - Release to iOS App Store
on:
  release:
    types: [published]

jobs:
# releaseToAppStore:
#   name: Release to the App Store
#   runs-on: macos-latest
#   needs: buildWithLinux
#   if: github.event.action == 'published' || (contains(github.event.inputs.mode, 'release') && contains(github.event.inputs.mode, 'ios'))
#   env:
#     APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
#     APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
#     APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
#     APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
#     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#     MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MATCH_PERSONAL_ACCESS_TOKEN }}
#     MATCH_URL: ${{ secrets.MATCH_URL }}
#     APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
#     APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
#     APPSTORE_P8: ${{ secrets. APPSTORE_P8 }}
#     APPSTORE_P8_PATH: ${{ format('{0}/fastlane/p8.json', github.workspace) }}
#     IOS_APP_ID: com.finoldigital.CardGameSim
#     IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
#     PROJECT_NAME: Card Game Simulator
#   steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
#     - name: Download iOS Artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: cgs-iOS
#         path: build/iOS
#     - name: Write to Changelog
#       if: github.event.action == 'published'
#       env:
#         RELEASE_NOTES: ${{ github.event.release.body }}
#       run: echo "$RELEASE_NOTES" > fastlane/metadata/android/en-US/changelogs/default.txt
#     - name: Fix File Permissions, Code-Sign, and Get Release Notes
#       id: terminal
#       run: |
#         find $IOS_BUILD_PATH -type f -name "**.sh" -exec chmod +x {} \;
#         find $IOS_BUILD_PATH -type f -iname "usymtool" -exec chmod +x {} \;
#         echo "$APPSTORE_P8" > $APPSTORE_P8_PATH
#         export notes="$(cat fastlane/metadata/android/en-US/changelogs/default.txt)"
#         notes="${notes//'%'/'%25'}"
#         notes="${notes//$'\n'/'%0A'}"
#         notes="${notes//$'\r'/'%0D'}"
#         echo "$notes"
#         echo "::set-output name=RELEASE_NOTES::$notes"
#     - name: Install Fastlane
#       run: bundle install
#     - name: Upload to the App Store
#       uses: maierj/fastlane-action@v2.0.1
#       env:
#         RELEASE_NOTES: ${{ steps.terminal.outputs.RELEASE_NOTES }}
#         USYM_UPLOAD_AUTH_TOKEN: ${{ secrets.USYM_UPLOAD_AUTH_TOKEN }}
#       with:
#         lane: 'ios release'