name: CD - Release to itch.io
on:
  release:
    types: [published]

jobs:
  release_webgl_to_itch:
  name: Release WebGL to itch.io
  runs-on: ubuntu-latest
  steps:
    - name: download WEBGL
      id: download-webgl
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "latest"
        file: build-WebGL.zip
        token: "${{ secrets.GH_CREDENTIALS }}"
    - name: deploy to itch.io (WEBGL)
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html
        ITCH_GAME: unity-ci-cd-tester
        ITCH_USER: Arynoyn
        PACKAGE: build-WebGL.zip
        VERSION: ${{ steps.download-webgl.outputs.version }}          

  release_windows_to_itch:
  name: Release Windows (32-Bit) to itch.io
  runs-on: ubuntu-latest
  steps:
    - name: download Windows
      id: download-windows
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "latest"
        file: build-StandaloneWindows.zip
        token: "${{ secrets.GH_CREDENTIALS }}"
    - name: deploy to itch.io (Windows)
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: unity-ci-cd-tester
        ITCH_USER: Arynoyn
        PACKAGE: build-StandaloneWindows.zip
        VERSION: ${{ steps.download-windows.outputs.version }}

  # release_windows_64_to_itch:
  # name: Release Windows (64-Bit) to itch.io
  # runs-on: ubuntu-latest
  # steps:
  #   - name: download Windows
  #     id: download-windows-64
  #     uses: dsaltares/fetch-gh-release-asset@master
  #     with:
  #       version: "latest"
  #       file: build-StandaloneWindows64.zip
  #       token: "${{ secrets.GH_CREDENTIALS }}"
  #   - name: deploy to itch.io (Windows)
  #     uses: josephbmanley/butler-publish-itchio-action@master
  #     env:
  #       BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  #       CHANNEL: windows
  #       ITCH_GAME: unity-ci-cd-tester
  #       ITCH_USER: Arynoyn
  #       PACKAGE: build-StandaloneWindows64.zip
  #       VERSION: ${{ steps.download-windows-64.outputs.version }}

  release_macos_to_itch:
    name: Release Mac OSX to itch.io
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: build-StandaloneOSX.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: unity-ci-cd-tester
          ITCH_USER: Arynoyn
          PACKAGE: build-StandaloneOSX.zip
          VERSION: ${{ steps.download-macos.outputs.version }}
  
  # release_linux_to_itch:
  #   name: Release Linux (64-bit) to itch.io
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: download Linux
  #       id: download-linux
  #       uses: dsaltares/fetch-gh-release-asset@master
  #       with:
  #         version: "latest"
  #         file: build-StandaloneLinux64.zip
  #         token: "${{ secrets.GH_CREDENTIALS }}"
  #     - name: deploy to itch.io (Linux)
  #       uses: josephbmanley/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  #         CHANNEL: linux
  #         ITCH_GAME: unity-ci-cd-tester
  #         ITCH_USER: Arynoyn
  #         PACKAGE: build-StandaloneLinux64.zip
  #         VERSION: ${{ steps.download-linux.outputs.version }}

  # release_Android_to_itch:
  #   name: Release Android to itch.io
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: download Android
  #       id: download-android
  #       uses: dsaltares/fetch-gh-release-asset@master
  #       with:
  #         version: "latest"
  #         file: build-Android.zip
  #         token: "${{ secrets.GH_CREDENTIALS }}"
  #     - name: deploy to itch.io (Android)
  #       uses: josephbmanley/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  #         CHANNEL: html
  #         ITCH_GAME: unity-ci-cd-tester
  #         ITCH_USER: Arynoyn
  #         PACKAGE: build-Android.zip
  #         VERSION: ${{ steps.download-android.outputs.version }}

  # release_html_to_itch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: download HTML5
  #       id: download-html
  #       uses: dsaltares/fetch-gh-release-asset@master
  #       with:
  #         version: "latest"
  #         file: build-html.zip
  #         token: "${{ secrets.GH_CREDENTIALS }}"
  #     - name: deploy to itch.io (HTML5)
  #       uses: josephbmanley/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  #         CHANNEL: html
  #         ITCH_GAME: unity-ci-cd-tester
  #         ITCH_USER: Arynoyn
  #         PACKAGE: build-html.zip
  #         VERSION: ${{ steps.download-html.outputs.version }}